### ISSUE TITLE
Add a new feature extractor

### ISSUE THREAD

**Issue by YilinGao-SHU** [bramtoula/vdna#1]
Greetings,

I would like to express my appreciation for releasing your work as an open-source project. This has significantly contributed to the advancement of relevant fields. May I inquire whether it is possible for you to provide a concise tutorial that elucidates how users can integrate their own feature extractors?

**Comment by bramtoula** [comment]
Hello,

Thank you for your interest in our work and your nice comments.
I think this is a good suggestion. I’m a bit busy right now, but I will try to write down a tutorial in the coming days.

**Comment by YilinGao-SHU** [comment]
> Hello,
> 
> Thank you for your interest in our work and your nice comments. I think this is a good suggestion. I’m a bit busy right now, but I will try to write down a tutorial in the coming days.

Thanks so much. :-)

**Comment by bramtoula** [comment]
Hello, and sorry for the delay!
I have added instructions with a basic example in [`docs/adding_your_feature_extractor.md`](https://github.com/bramtoula/vdna/blob/08fff7c12a427f22fded2d37a8db7eb72ae9da83/docs/adding_your_feature_extractor.md).
Please don't hesitate to let me know if you have any questions.
