### ISSUE TITLE
Can't pickle local object 'make_resizer.<locals>.func'

### ISSUE THREAD

**Issue by adriengoleb** [bramtoula/vdna#3]
Hi,

I have the error ```Can't pickle local object 'make_resizer.<locals>.func``` when I launch the code ```emd = EMD(vdna1, vdna2)```

I'm guessing that the error comes from the pickle module, which I don't want to use. 

Even, when I add the option ```weights_only=True``` in the function ```torch.load``` in the ```mugs_vit.py```, I have the same problem ....

Thanks for the help !

**Comment by bramtoula** [comment]
Hi,
I've looked into this and managed to reproduce it in a specific environment.
It seems like it might be linked to some issues with the multiprocessing used by the torch dataloader on some specific systems.

Could you please try setting the number of workers to 0 when creating `vdna1` and `vdna2` and let me know if the issue still happens?

```
vdna = vdna_proc.make_vdna(source="/path/to/dataset", num_workers=0)
```

If you could also let me know which OS you are using so I can confirm where this doesn't work, that'd be great!

Thank you!

**Comment by adriengoleb** [comment]
Thanks for the quick feedback!

The error has disappeared by specifying this parameter. It's logic because I didn't want to work on multiple device.
For information, I'm on Windows

Thanks for all your help !

**Comment by bramtoula** [comment]
Great, happy that solved it! And thank you for confirming your OS.

I will make sure to use that as the default in the future to prevent this issue.
